name = str(input("Ваші прізвище, ім'я, по батькові? "))
age = str(input("Скільки Вам років? "))
location = str(input("Де Ви живете? "))
study = str(input("Де Ви навчаєтесь? "))
groupNumber = str(input("Номер Вашої групи? "))
serialNumber = str(input("Який Ваш порядковий номер у списку групи? "))

tableQuestion0 = str(input("Як справи? "))
tableQuestion1 = str(input("Як Ви себе почуваєте? "))
tableQuestion2 = str(input("Коли будете вдома? "))
tableQuestion3 = str(input("Яку оцінку отримав на ЗНО по українській мові? "))
tableQuestion4 = str(input("Сьогодні сонячно?  "))
tableQuestion5 = str(input("Коли нарешті карантин? "))
tableQuestion6 = str(input("Як звати Вашого друга? "))
tableQuestion7 = str(input("Ви думаєте вступати у магістратуру? "))
tableQuestion8 = str(input("Якого кольору Ваш зошит? "))
tableQuestion9 = str(input("Який Ваш настрій сьогодні? "))

print(f"Ваше ім'я {name}")
print(f"Ваш вік {age}")
print(f"Ви живете в {location}")
print(f"Ви навчаєтесь в місті/селі {study}")
print(f"Номер Вашої групи - {groupNumber}")
print(f"Ваш порядковий номер у списку групи - {serialNumber}")